# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/ocr_receipt.ipynb (unless otherwise specified).

__all__ = ['parse_args']

# Cell
import io
import os
from google.cloud import vision
from datetime import datetime
import argparse

# Cell
def parse_args():
    parser = argparse.ArgumentParser(description="OCR image processing")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("-r", "--random", action="store_true", help="Select a random image")
    group.add_argument("-p", "--path", type=str, help="Specify the path of the image")
    parser.add_argument("-q", "--quiet", action="store_true", help="Suppress the output")
    return parser.parse_args()